config/routes.rb
Rails.application.routes.draw do
  resources :searches



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show

  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create

    search_term = search_params['keyword']
    category_term = search_params['category']
    byebug
    if search_term != ""
      response = RestClient.get "https://api.chucknorris.io/jokes/search?query=#{search_term}"
      json = JSON.parse(response)
      if !json['total'].zero?
        @objects = json["result"]
        @objects.paginate(:page => params[:page], :per_page => 30)
        params[:content] = json["result.value"]
        @search = Search.new(search_params)

      else
        render :new
      end
    else
      response = RestClient.get "https://api.chucknorris.io/jokes/random?category=#{category_term}"
      json = JSON.parse(response)
      if !json['categories'].nil?
        @objects_category = json["value"]
      else
        render :new
      end
    end
    end



  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keyword, :category, :random, :content)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InspiringTestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :random %>
    <%= form.number_field :random %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/create.html.erb
<% if @objects.present? %>
  <% @objects.each do |object|%>
    <%= object["value"] %>
    <br><br><br>
  <% end %>
<% end %>

<% if @objects_category.present? %>
    <%= @objects_category %>
    <br><br><br>

<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Category</th>
      <th>Random</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.keyword %></td>
        <td><%= search.category %></td>
        <td><%= search.random %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @search.keyword %>
</p>

<p>
  <strong>Category:</strong>
  <%= @search.category %>
</p>

<p>
  <strong>Random:</strong>
  <%= @search.random %>
</p>

<h1><%= params['keyword'].capitalize %>:</h1>
<% @objects.each do |object|%>
  <h2> <%= object["title"] %><</h2>
<% end %>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>